[package]
authors = ["The Rust Project Developers"]
name = "pan_index"
version = "0.0.0"
edition = "2018"

[lib]
doctest = false

[dependencies]
arrayvec = { version = "0.5.1", default-features = false }
pan_serialize = { path = "../pan_serialize" }
pan_macros = { path = "../pan_macros" }
