[package]
authors = ["The Rust Project Developers"]
name = "pan_feature"
version = "0.0.0"
edition = "2018"

[lib]
doctest = false

[dependencies]
pan_data_structures = { path = "../pan_data_structures" }
pan_span = { path = "../pan_span" }
