[package]
name = "pan-vm"
version = "0.1.0"
authors = ["潘振兴 <panzhenxing551@gmail.com>"]
edition = "2018"

[features]
default = ["pan-parser", "pan-compiler"]
vm-tracing-logging = []
freeze-stdlib = []

[dependencies]
digest = "0.8.1"
md-5 = "0.8"
sha-1 = "0.8"
sha2 = "0.8"
sha3 = "0.8"
blake2 = "0.8"
volatile = "0.2"

num-complex = { version = "0.2.2", features = ["serde"] }
num-bigint = { version = "0.2.4", features = ["serde"] }
num-traits = "0.2.8"
num-integer = "0.1.41"
num-rational = "0.2.2"
num-iter = "0.1.39"
rand = { version = "0.7", features = ["wasm-bindgen"] }
rand_core = "0.5"
getrandom = { version = "0.1", features = ["wasm-bindgen"] }
log = "0.4"
pan-parser = {path = "../parser", optional = true, version = "0.1.0"}
pan-compiler = {path = "../compiler", optional = true, version = "0.1.0"}
pan-bytecode = { path = "../bytecode", version = "0.1.0"}
serde = { version = "1.0.66", features = ["derive"] }
serde_json = "1.0.26"
byteorder = "1.2.6"
regex = "1"
rustc_version_runtime = "0.1.*"
statrs = "0.12.0"
caseless = "0.2.1"
chrono = { version = "=0.4.9", features = ["wasmbind"] }
once_cell = "1.3.1"
lexical = "4"
itertools = "0.8"
hex = "0.4.0"
hexf-parse = "0.1.0"
indexmap = "1.0.2"
crc = "^1.0.0"
unicode_names2 = "0.3"

unicode-casing = "0.1"
unic = "0.9"
unic-common = "0.9"
maplit = "1.0"
bitflags = "1.2.1"
libc = "0.2"
nix = "0.16.0"
arr_macro = "0.1.2"
csv = "1.1.1"
paste = "0.1"
base64 = "0.11"
is-macro = "0.1"
result-like = "^0.2.1"

