[package]
name = "pan_type_ir"
version = "0.0.0"
authors = ["The Rust Project Developers"]
edition = "2018"

[lib]
doctest = false

[dependencies]
bitflags = "1.2.1"
pan_index = { path = "../pan_index" }
pan_serialize = { path = "../pan_serialize" }
pan_data_structures = { path = "../pan_data_structures" }
