[package]
authors = ["The Rust Project Developers"]
name = "pan_span"
version = "0.0.0"
edition = "2018"

[lib]
doctest = false

[dependencies]
pan_serialize = { path = "../pan_serialize" }
pan_macros = { path = "../pan_macros" }
pan_data_structures = { path = "../pan_data_structures" }
pan_index = { path = "../pan_index" }
pan_arena = { path = "../pan_arena" }
scoped-tls = "1.0"
unicode-width = "0.1.4"
cfg-if = "0.1.2"
tracing = "0.1"
sha-1 = "0.9"
sha2 = "0.9"
md-5 = "0.9"
