[package]
authors = ["The Rust Project Developers"]
name = "pan_serialize"
version = "0.0.0"
edition = "2018"

[dependencies]
indexmap = "1"
smallvec = { version = "1.0" }

[dev-dependencies]
pan_macros = { path = "../pan_macros" }
