[package]
authors = ["The Rust Project Developers"]
name = "pan_ast_pretty"
version = "0.0.0"
edition = "2018"

[lib]
doctest = false

[dependencies]
tracing = "0.1"
pan_span = { path = "../pan_span" }
pan_ast = { path = "../pan_ast" }
pan_target = { path = "../pan_target" }
