[package]
authors = ["The Rust Project Developers"]
name = "pan_typeck"
version = "0.0.0"
edition = "2018"

[lib]
test = false
doctest = false

[dependencies]
pan_arena = { path = "../pan_arena" }
tracing = "0.1"
pan_macros = { path = "../pan_macros" }
pan_middle = { path = "../pan_middle" }
pan_attr = { path = "../pan_attr" }
pan_data_structures = { path = "../pan_data_structures" }
pan_errors = { path = "../pan_errors" }
pan_hir = { path = "../pan_hir" }
pan_hir_pretty = { path = "../pan_hir_pretty" }
pan_target = { path = "../pan_target" }
pan_session = { path = "../pan_session" }
smallvec = { version = "1.0", features = ["union", "may_dangle"] }
pan_ast = { path = "../pan_ast" }
pan_span = { path = "../pan_span" }
pan_index = { path = "../pan_index" }
pan_infer = { path = "../pan_infer" }
pan_trait_selection = { path = "../pan_trait_selection" }
