[package]
authors = ["The Rust Project Developers"]
name = "pan_ty_utils"
version = "0.0.0"
edition = "2018"

[dependencies]
tracing = "0.1"
pan_middle = { path = "../pan_middle" }
pan_data_structures = { path = "../pan_data_structures" }
pan_errors = { path = "../pan_errors" }
pan_hir = { path = "../pan_hir" }
pan_infer = { path = "../pan_infer" }
pan_span = { path = "../pan_span" }
pan_session = { path = "../pan_session" }
pan_target = { path = "../pan_target" }
pan_trait_selection = { path = "../pan_trait_selection" }
