[package]
authors = ["The Rust Project Developers"]
name = "pan_symbol_mangling"
version = "0.0.0"
edition = "2018"

[lib]
doctest = false

[dependencies]
tracing = "0.1"
punycode = "0.4.0"
rustc-demangle = "0.1.18"

pan_ast = { path = "../pan_ast" }
pan_span = { path = "../pan_span" }
pan_middle = { path = "../pan_middle" }
pan_hir = { path = "../pan_hir" }
pan_target = { path = "../pan_target" }
pan_data_structures = { path = "../pan_data_structures" }
pan_session = { path = "../pan_session" }
