[package]
authors = ["The Rust Project Developers"]
name = "pan_save_analysis"
version = "0.0.0"
edition = "2018"

[dependencies]
tracing = "0.1"
pan_middle = { path = "../pan_middle" }
pan_ast = { path = "../pan_ast" }
pan_ast_pretty = { path = "../pan_ast_pretty" }
pan_data_structures = { path = "../pan_data_structures" }
pan_hir = { path = "../pan_hir" }
pan_hir_pretty = { path = "../pan_hir_pretty" }
pan_lexer = { path = "../pan_lexer" }
serde_json = "1"
pan_session = { path = "../pan_session" }
pan_span = { path = "../pan_span" }
rls-data = "0.19"
rls-span = "0.5"
