[package]
authors = ["The Rust Project Developers"]
name = "pan_session"
version = "0.0.0"
edition = "2018"

[dependencies]
bitflags = "1.2.1"
getopts = "0.2"
pan_macros = { path = "../pan_macros" }
tracing = "0.1"
pan_errors = { path = "../pan_errors" }
pan_feature = { path = "../pan_feature" }
pan_target = { path = "../pan_target" }
pan_serialize = { path = "../pan_serialize" }
pan_data_structures = { path = "../pan_data_structures" }
pan_span = { path = "../pan_span" }
pan_fs_util = { path = "../pan_fs_util" }
num_cpus = "1.0"
pan_ast = { path = "../pan_ast" }
pan_lint_defs = { path = "../pan_lint_defs" }
