[package]
authors = ["The Rust Project Developers"]
name = "pan_traits"
version = "0.0.0"
edition = "2018"

[dependencies]
tracing = "0.1"
pan_middle = { path = "../pan_middle" }
pan_data_structures = { path = "../pan_data_structures" }
pan_hir = { path = "../pan_hir" }
pan_index = { path = "../pan_index" }
pan_ast = { path = "../pan_ast" }
pan_span = { path = "../pan_span" }
chalk-ir = "0.36.0"
chalk-solve = "0.36.0"
chalk-engine = "0.36.0"
smallvec = { version = "1.0", features = ["union", "may_dangle"] }
pan_infer = { path = "../pan_infer" }
pan_trait_selection = { path = "../pan_trait_selection" }
