[package]
authors = ["The Rust Project Developers"]
name = "pan_target"
version = "0.0.0"
edition = "2018"

[dependencies]
bitflags = "1.2.1"
tracing = "0.1"
pan_data_structures = { path = "../pan_data_structures" }
pan_macros = { path = "../pan_macros" }
pan_serialize = { path = "../pan_serialize" }
pan_span = { path = "../pan_span" }
pan_index = { path = "../pan_index" }
